### PR TITLE
added yaml support to expend_keys, #54

### PR DESCRIPTION
**Pull request by hexelon**

### CODE REVIEW

**Comment by stevenscg** [comment]
This looks like a great feature! Many of us prefer or at least use yaml and parity with json for key expansion would be very nice to have.

I am planning a conversion of a large number of configuration parameters over the next week or so. Many of those are already in yaml files for consumption via Ansible and could likely be reused as-is.

**Comment by calvn** [comment]
Can we get some tests for this?

**Comment by stevenscg** [comment]
@hexelon @calvn I'm probably not the best to build you a real test case, but I just ran a manual test scenario and will be actively working with git2consul and hopefully using yml files over the next day or two.

I tried to the branch from this PR, but did not observe any changes from the current upstream git2consul version from npm.

I have a file `foo.yml` in a private `config` repo out on github:
```yaml
---
enabled: true
app_id: '123456787'
```

git2consul.json:
```json
{
  "version": "1.0",
  "repos": [{
    "name": "config",
    "url": "git@github.com:XXXX/config.git",
    "branches": ["dev"],
    "include_branch_name": false,
    "ignore_file_extension": true,
    "mode": "expand_keys",
    "debug": true,
    "hooks": [{
      "type" : "polling",
      "interval" : "1"
    }]
  }]
}

```

I uninstalled the npm version and ran yours directly:
```
node -v
v0.12.15

node /home/vagrant/git2consul/index.js --config-file ./git2consul.json
```

The above starts up without any errors.

I expected to find `/v1/kv/config/foo/enabled` set, but the `foo` yml is not unpacked:
```
curl consul.service.consul:8500/v1/kv/config/foo?raw
---

enabled: true
app_id: '123456787'
```

**Comment by hexelon** [comment]
@stevenscg the following configuration is working for me:

{
  "version": "1.0",
  "mode": "expand_keys",
  "repos" : [{
    "name" : "config",
    "expand_keys": true,
    "ignore_file_extension": true,
    "url" : "xxx",
    "branches" : ["master"],
    "include_branch_name" : false
  }]
}

If i remember correctly adding "expand_keys": true made the trick for me.

**Comment by stevenscg** [comment]
@hexelon Thanks! That was it exactly.

In fact, I added `expand_keys: true` and removed `mode: "expand_keys"` and tested the correct yaml expansion operation.

My working config is:
```json
{
  "version": "1.0",
  "repos": [{
    "name": "config",
    "url": "git@github.com:XXXX/config.git",
    "branches": ["dev"],
    "include_branch_name": false,
    "ignore_file_extension": true,
    "expand_keys": true,
    "debug": true,
    "hooks": [{
      "type" : "polling",
      "interval" : "1"
    }]
  }]
}
```

@calvn, do you know if the `mode` attribute is currently functional? It doesn't seem to matter here in this case, the test cases use `expand_keys: true`.

The `github_data` example in the [README](https://github.com/Cimpress-MCP/git2consul#configuration-format) uses it and led me astray.

**Comment by calvn** [comment]
@stevenscg according to [this commit](https://github.com/Cimpress-MCP/git2consul/commit/8d4b4577e27cfe61e34555b1af2d4241d1128f3e) the `mode` attribute was removed in favor of `expand_keys: true`. The example in the README is indeed incorrect.

**Comment by stevenscg** [comment]
Got it. Good find. If we can't pick up the README change on this branch, I'll do a docs PR separately.

**Comment by stevenscg** [comment]
I didn't notice this previously, but when running with this branch, repo polling is not actually being established and the git2consul process exits after populating the keys correctly the first time.

Basically, I see the log entries for "Initting branch" and "Initting repo", but none of these:
```json
{"name":"git2consul","hostname":"localhost.localdomain","pid":4344,"level":20,"msg":"Polling hook initialized with 1 minute intervals","time":"2016-08-18T20:11:54.494Z","v":0}
{"name":"git2consul","hostname":"localhost.localdomain","pid":4344,"level":30,"msg":"Loaded repo config","time":"2016-08-18T20:11:54.495Z","v":0}
...
{"name":"git2consul","hostname":"localhost.localdomain","pid":4344,"level":20,"msg":"Updates in branch dev complete","time":"2016-08-18T20:13:04.884Z","v":0}
```

Example startup with this branch on exactly the same config and repo:
```
{"name":"git2consul","hostname":"localhost.localdomain","pid":4609,"level":30,"msg":"git2consul is running","time":"2016-08-18T20:16:08.401Z","v":0}
{"name":"git2consul","hostname":"localhost.localdomain","pid":4609,"level":30,"msg":"Initting repo config","time":"2016-08-18T20:16:08.404Z","v":0}
{"name":"git2consul","hostname":"localhost.localdomain","pid":4609,"level":30,"msg":"Initting branch /tmp/config /tmp/config/dev","time":"2016-08-18T20:16:08.404Z","v":0}
{"name":"git2consul","hostname":"localhost.localdomain","pid":4609,"level":20,"msg":"Expandable file config/foo yielded 2 keys","time":"2016-08-18T20:16:09.177Z","v":0}
```

I'm running with `debug` level logging, but not seeing any errors or details when the exit occurs.

Suggestions?

**Comment by stevenscg** [comment]
Sorry all, the above comment might be a false alarm. It seems to be working at the moment, but this isn't a clean install anymore so I'll just monitor it for a while.

**Comment by calvn** [comment]
This is implemented in #95 so I'm going to close this.

**Pull request closed without merging**
