### PR TITLE
Add gitlab webhook

### PR DESCRIPTION
**Pull request by llange**
Here is a tentative implementation of Gitlab's webhook, according to https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md .

### CODE REVIEW

**Comment by ryanbreen** [comment]
Very cool!  Thanks for doing this and including a thorough test case.

**Comment by ryanbreen** [comment]
This is published in NPM as 0.8.0.

**Comment by llange** [comment]
I forgot to edit readme.md to inform about this webhook. Should I make another pull request or is it still possible to enhance this one ?

**Comment by ryanbreen** [comment]
I already added it.

**Comment by ryanbreen** [comment]
I should say, I added a mention to Gitlab and a link to the docs.  I did not include a sample.  If you would like to include a sample, I think that'll need to be a new PR since this one is closed.

**Comment by llange** [comment]
Thanks for the readme, it's perfect.
I don't have a specific sample to add.

**Pull request merged**
