### PR TITLE
Add `ignore_repo_name` config option.

### PR DESCRIPTION
**Pull request by eyalzek**

### CODE REVIEW

**Comment by bitsofinfo** [comment]
+1, please merge this! :)

**Comment by nfedyk** [comment]
+1

**Comment by bmudda** [comment]
+1

**Comment by calvn** [comment]
I'll be taking in this PR in favor of #100 since this is a feature that is true-by-default, so it makes sense that the option would be to ignore the branch name if set, similar to `ignore_file_extension`. At the end of the day, both implementations yields the same end result. @eyalzek and @David-V2 thank you both for the contribution!

**Pull request merged**
