### PR TITLE
Add support for tags

### PR DESCRIPTION
**Pull request by kalistace**
When activated, tags will be treated as if they were branches and are picked up dynamically by the hook

### CODE REVIEW

**Comment by ryanbreen** [comment]
Very cool!

I'll take a look, thanks.

**Comment by ryanbreen** [comment]
Can you explain why you prefer to have this change at hook level rather than repo/branch level? At repo level, we could do all the same logic here but support repos that don't use polling books.

**Comment by kalistace** [comment]
To be honest, I completely forgot about webhooks. Therefore, I just assumed polling was the only option.

Thanks for pointing that out, you're right, we probably should put that option at the repo/branch level.

How should we name that option then ? `support_tags` ?

**Comment by ryanbreen** [comment]
Yep, that seems like a good name for this switch.

**Comment by kalistace** [comment]
Cool, I just made these changes :)

**Comment by ryanbreen** [comment]
This is so completely well done!  Great documentation, thorough tests.

Only ask I have before merging is that you provide a bit of documentation in `lib/git/hooks/polling.js` to explain the need for `start_delayed_updater`.  Also, if you could correct the indentation so that entire block of `exports.init` doesn't appear to have been modified, that would be really helpful.

**Comment by kalistace** [comment]
Sure ! I just fixed the indentation. Regarding the documentation, I've moved up the already existing comment block. Not sure if that's enough ?

Thanks for reviewing all this :)

**Comment by ryanbreen** [comment]
Ahh, that makes sense.  Looks great!

**Comment by kalistace** [comment]
Excellent ! Thanks for merging it. It's been a pleasure contributing to this project.

**Comment by ryanbreen** [comment]
Any time!

This is published as 0.11.0.

**Comment by mayusuk** [comment]
little demo on how to use tags will be awesome.

**Pull request merged**
