### PR TITLE
Adding a Dockerfile

### PR DESCRIPTION
**Pull request by voxxit**
Since we use Docker in our production environment, I thought it would be useful to have a Dockerfile which we could use to run git2consul on ECS to automatically replicate our KV configuration to multiple datacenters automatically when it changes.

I have included `example.json` in this PR, but happy to take it out before you merge — just wanted to give a good usage example. Save the following to `example.json`:

```
{
  "version": "1.0",
  "repos" : [
    {
      "name" : "orders",
      "expand_keys": true,
      "url" : "https://github.com/voxxit/git2consul-example.git",
      "branches" : [
        "production",
        "staging"
      ],
      "hooks" : [
        {
          "type" : "polling",
          "interval" : "1"
        }
      ]
    }
  ]
}
```

Run consul locally on your machine to test this out:

```
consul agent -data-dir /tmp/consul -bootstrap -server -advertise=<your IP> -client=<your IP>
```

Then, you can pull & run the Docker image:

```
docker pull voxxit/git2consul:latest
docker run --rm -it --net=host -e CONSUL_ENDPOINT=<your IP> -v ${PWD}/example.json:/etc/git2consul.json voxxit/git2consul:latest
```

And, voila!

```
{"name":"git2consul","hostname":"docker","pid":1,"level":30,"msg":"git2consul is running","time":"2016-05-03T13:15:16.069Z","v":0}
{"name":"git2consul","hostname":"docker","pid":1,"level":30,"msg":"Initting repo orders","time":"2016-05-03T13:15:16.073Z","v":0}
{"name":"git2consul","hostname":"docker","pid":1,"level":30,"msg":"Initting branch /tmp/orders /tmp/orders/production","time":"2016-05-03T13:15:16.073Z","v":0}
{"name":"git2consul","hostname":"docker","pid":1,"level":30,"msg":"Initting branch /tmp/orders /tmp/orders/staging","time":"2016-05-03T13:15:16.074Z","v":0}
{"name":"git2consul","hostname":"docker","pid":1,"level":40,"msg":"Purging branch cache /tmp/orders/production for branch production in repo orders","time":"2016-05-03T13:15:16.074Z","v":0}
{"name":"git2consul","hostname":"docker","pid":1,"level":40,"msg":"Purging branch cache /tmp/orders/staging for branch staging in repo orders","time":"2016-05-03T13:15:16.075Z","v":0}
{"name":"git2consul","hostname":"docker","pid":1,"level":30,"msg":"Initialized branch production from orders","time":"2016-05-03T13:15:17.052Z","v":0}
{"name":"git2consul","hostname":"docker","pid":1,"level":30,"msg":"Initialized branch staging from orders","time":"2016-05-03T13:15:17.055Z","v":0}
{"name":"git2consul","hostname":"docker","pid":1,"level":30,"msg":"Loaded repo orders","time":"2016-05-03T13:15:17.057Z","v":0}
```

**NOTE:** Pulls from https://github.com/voxxit/git2consul-example!

### CODE REVIEW

**Comment by cleung2010** [comment]
@voxxit thanks for providing an example of running git2consul with Docker! We are also running git2consul on ECS as well, and have a Dockerfile for git2consul publicly available. It is separate from this repo, but maybe we should link it in the Readme. https://github.com/Cimpress-MCP/docker-git2consul

**Comment by voxxit** [comment]
@cleung2010 Ah, yes, that would have been helpful :) I believe it makes most sense to keep the Dockerfile with the repo itself, though, no?

**Comment by cleung2010** [comment]
I think it depends from project to project. For example, hashicorp/consul itself doesn't contain a Dockerfile. Keeping components as modular/lean as possible not a bad thing from an organizational standpoint :)

**Comment by cleung2010** [comment]
Actually, since docker-git2consul gets pinned to a particular build and there is not much changes apart from that, it wouldn't be a bad idea to include it in the repo and have CI publish the new image version whenever a new package version is released. However, I think for now linking to docker-git2consul should suffice.

**Comment by cleung2010** [comment]
Closing since Docker image will live under https://github.com/Cimpress-MCP/docker-git2consul. Feel free to make changes/adjustments there.

**Pull request closed without merging**
