### PR TITLE
Add an 'include_repo_name' feature

### PR DESCRIPTION
**Pull request by David-V2**
- Add an 'include_repo_name' feature, not unlike the 'include_branch_name' one
- Update README.md
- Add some tests
- Probably need more tests, I don't fully understand the entire app, I'm not a javascript dev

### CODE REVIEW

**Comment by bitsofinfo** [comment]
+1

**Comment by bitsofinfo** [comment]
related, could be confusing to have both? https://github.com/Cimpress-MCP/git2consul/pull/113

**Comment by eyalzek** [comment]
Huh, I missed this PR. Inverted functionality, but achieves the same in the end of the day :)

**Comment by calvn** [comment]
@bitsofinfo agreed, will probably merge one of the two. I have been carried away recently with other things, but will take a closer look soon.

**Comment by bitsofinfo** [comment]
@calvn great, would love to see this in, have a need for it right now :)

**Comment by calvn** [comment]
Implemented in #113

**Pull request closed without merging**
